name: Build and Deploy to GKE

on:
  push:
    branches: [ master ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_LOCATION: ${{ secrets.GKE_LOCATION }}
  REGISTRY: europe-central2-docker.pkg.dev
  REPO_NAME: books-repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
            credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
            project_id: ${{ env.PROJECT_ID }}

      - name: Install gke-gcloud-auth-plugin
        run: |
            curl -LO https://github.com/googlecloudplatform/gke-gcloud-auth-plugin/releases/latest/download/gke-gcloud-auth-plugin_linux_amd64
            chmod +x gke-gcloud-auth-plugin_linux_amd64
            mkdir -p ~/.config/gcloud/
            mv gke-gcloud-auth-plugin_linux_amd64 ~/.config/gcloud/
            export PATH="$HOME/.config/gcloud:$PATH"
            echo 'export PATH="$HOME/.config/gcloud:$PATH"' >> $GITHUB_ENV

      - name: Configure Docker auth for GCR
        run: gcloud auth configure-docker $REGISTRY --quiet

      - name: Build and push frontend image
        run: |
          IMAGE_TAG="$REGISTRY/$PROJECT_ID/$REPO_NAME/frontend:${{ github.sha }}"
          docker build -t "$IMAGE_TAG" -f ./frontend/Dockerfile ./frontend
          docker push "$IMAGE_TAG"

      - name: Build and push gateway image
        run: |
          IMAGE_TAG="$REGISTRY/$PROJECT_ID/$REPO_NAME/gateway:${{ github.sha }}"
          docker build -t "$IMAGE_TAG" -f ./gateway/Dockerfile ./gateway
          docker push "$IMAGE_TAG"

      - name: Build and push books-service image
        run: |
          IMAGE_TAG="$REGISTRY/$PROJECT_ID/$REPO_NAME/books-service:${{ github.sha }}"
          docker build -t "$IMAGE_TAG" -f ./books-service/Dockerfile ./books-service
          docker push "$IMAGE_TAG"

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials "$CLUSTER_NAME" --zone "$GKE_LOCATION" --project "$PROJECT_ID"

      - name: Update deployments in GKE
        run: |
          FRONTEND_IMAGE="$REGISTRY/$PROJECT_ID/$REPO_NAME/frontend:${{ github.sha }}"
          GATEWAY_IMAGE="$REGISTRY/$PROJECT_ID/$REPO_NAME/gateway:${{ github.sha }}"
          BOOKS_IMAGE="$REGISTRY/$PROJECT_ID/$REPO_NAME/books-service:${{ github.sha }}"

          kubectl -n books set image deployment/frontend frontend="$FRONTEND_IMAGE"
          kubectl -n books set image deployment/gateway gateway="$GATEWAY_IMAGE"
          kubectl -n books set image deployment/books-service books-service="$BOOKS_IMAGE"

          kubectl -n books rollout status deployment/frontend
          kubectl -n books rollout status deployment/gateway
          kubectl -n books rollout status deployment/books-service
